### ISSUE TITLE
How to crawl all papers from various conferences without entering keywords？

### ISSUE THREAD

**Issue by maofan44** [sucv/paperCrawler#1]
Hey，bro，How to crawl all papers from various conferences without entering keywords？

**Comment by sucv** [comment]
-keys “”

should let you get all the papers.

**Comment by maofan44** [comment]
hey，bro，I found that typing -key'' can only crawl some papers, I try to reduce the access speed and download speed in the settings.py, but I still can't crawl all papers

**Comment by sucv** [comment]
It was fixed recently. Please check the new version.
